---
###############################################################################
# NPM APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v1.4.3'
  - project: 'customers/coghent/infra/coghent-infra-gitlab-templates'
    file    : 'dams-dev-deploy.yml'
    ref     : 'master'
    
variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-frontend'
  TERRAFORM_IMAGE: 'dams-terraform'
  TERRAFORM_TAG: 'latest'
  SKIP_DEPLOY: 'true'
