---
###############################################################################
# NPM APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v1.5.4'
  - project: 'rnd/inuits/dams/pipeline-deploy-targets'
    file: 'extra-targets.yml'
    ref: 'main'

variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-frontend'
  SKIP_DEPLOY: 'true'
