---
###############################################################################
# NPM APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v3.2.0'

variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-frontend'
  SKIP_DEPLOY: 'true'
