---

# --------------------------------------------------------------
# Includes
# --------------------------------------------------------------
include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    ref: 'v4.0.0'
    file: 
      - 'pipelines/customers/deploy.yml'
      - 'jobs/docker/build-npm.yml'


# --------------------------------------------------------------
# Variables
# --------------------------------------------------------------
variables:
  CUSTOMER: inuits
  PROJECT: dams
  APPLICATION: frontend

  SKIP_DEPLOY: 'true'

  HARBOR_PROJECT_DEV: elody-dams-dev
  TARGET_CLUSTER_DEV: inuits-prod


# --------------------------------------------------------------
# Template overrides
# --------------------------------------------------------------

# Disable uat, not needed
uat:
  rules:
    - when: never

# Disable prod, not needed
prod:
  rules:
    - when: never
