import {
  uniEdit,
  uniEye,
  uniFileDownload,
  uniSearchPlus,
  uniSearchMinus,
  uniDesktop,
  uniAngleLeft,
  uniAngleRight,
  uniAngleDown,
  uniBookOpen,
  uniUser,
  uniSearch,
  uniPlusCircle,
} from 'vue-unicons/dist/icons';

export enum Unicons {
  Edit = uniEdit,
  Eye = uniEye,
  Download = uniFileDownload,
  SearchPlus = uniSearchPlus,
  SearchMinus = uniSearchMinus,
  Desktop = uniDesktop,
  AngleLeft = uniAngleLeft,
  AngleRight = uniAngleRight,
  AngleDown = uniAngleDown,
  BookOpen = uniBookOpen,
  User = uniUser,
  SearchGlass = uniSearch,
  PlusCircle = uniPlusCircle,
}
