import type { DamsIcons } from "@/generated-types/queries";
import {
  uniAngleDoubleLeft,
  uniAngleDoubleRight,
  uniAngleDown,
  uniAngleLeft,
  uniAngleRight,
  uniAngleUp,
  uniApps,
  uniArchiveAlt,
  uniArrow,
  uniArrowCircleLeft,
  uniArrowCircleRight,
  uniBan,
  uniBars,
  uniBookOpen,
  uniBrightnessPlus,
  uniCar,
  uniChannel,
  uniCheck,
  uniCheckCircle,
  uniCheckSquare,
  uniCircle,
  uniCog,
  uniCloudBookmark,
  uniCloudDataConnection,
  uniCloudUpload,
  uniCompass,
  uniCreateDashboard,
  uniDatabase,
  uniDesktop,
  uniDesktopSlash,
  uniDocumentInfo,
  uniDownloadAlt,
  uniDraggabledots,
  uniEdit,
  uniEditAlt,
  uniEllipsisH,
  uniEllipsisV,
  uniEllipsisVThinline,
  uniExclamationTriangle,
  uniExport,
  uniEye,
  uniEyeSlash,
  uniFileAlt,
  uniFileDownload,
  uniFileEditAlt,
  uniFileExport,
  uniFileInfoAlt,
  uniFilter,
  uniFocus,
  uniFocusTarget,
  uniFolder,
  uniFont,
  uniGlobe,
  uniHdd,
  uniHistory,
  uniHome,
  uniImage,
  uniImageCheck,
  uniImagePlus,
  uniImageSlash,
  uniImageResizeLandscape,
  uniInfoCircle,
  uniKeyholeSquareFull,
  uniLink,
  uniListOl,
  uniListUl,
  uniLocationArrowAlt,
  uniLocationPoint,
  uniMap,
  uniMapMarker,
  uniMapMarkerInfo,
  uniMapPin,
  uniMinus,
  uniMultiply,
  uniMusic,
  uniPause,
  uniPlay,
  uniPlus,
  uniPlusCircle,
  uniProcess,
  uniProcessor,
  uniQuestionCircle,
  uniRedo,
  uniSave,
  uniSearch,
  uniSearchMinus,
  uniSearchPlus,
  uniSetting,
  uniSignout,
  uniSort,
  uniSortAmountDown,
  uniSortAmountUp,
  uniSquareFull,
  uniSwatchbook,
  uniTag,
  uniText,
  uniTimes,
  uniTimesCircle,
  uniTrashAlt,
  uniUser,
  uniUserCircle,
  uniUserSquare,
  uniVideoSlash,
  uniVolume,
  uniWindowGrid,
  uniWindowMaximize,
  uniCopy,
  uniKeyboard,
  uniCropAlt,
  uniCancel,
} from "vue-unicons/dist/icons";

export const Unicons: Record<DamsIcons, { name: string }> = {
  NoIcon: { name: "" },
  AngleDoubleLeft: uniAngleDoubleLeft,
  AngleDoubleRight: uniAngleDoubleRight,
  AngleDown: uniAngleDown,
  AngleLeft: uniAngleLeft,
  AngleRight: uniAngleRight,
  AngleUp: uniAngleUp,
  Apps: uniApps,
  ArchiveAlt: uniArchiveAlt,
  Arrow: uniArrow,
  ArrowCircleLeft: uniArrowCircleLeft,
  ArrowCircleRight: uniArrowCircleRight,
  AudioThumbnail: uniVolume,
  Ban: uniBan,
  Bars: uniBars,
  BookOpen: uniBookOpen,
  BrightnessPlus: uniBrightnessPlus,
  Car: uniCar,
  Channel: uniChannel,
  Cancel: uniCancel,
  Crop: uniCropAlt,
  Check: uniCheck,
  CheckCircle: uniCheckCircle,
  CheckSquare: uniCheckSquare,
  Circle: uniCircle,
  Close: uniMultiply,
  CloudBookmark: uniCloudBookmark,
  CloudDataConnection: uniCloudDataConnection,
  Compass: uniCompass,
  Create: uniCreateDashboard,
  Cross: uniTimes,
  CrossCircle: uniTimesCircle,
  Cog: uniCog,
  Database: uniDatabase,
  Desktop: uniDesktop,
  DesktopSlash: uniDesktopSlash,
  DocumentInfo: uniDocumentInfo,
  Download: uniFileDownload,
  DownloadAlt: uniDownloadAlt,
  Draggabledots: uniDraggabledots,
  Edit: uniEdit,
  EditAlt: uniEditAlt,
  EllipsisH: uniEllipsisH,
  EllipsisV: uniEllipsisV,
  EllipsisVThinline: uniEllipsisVThinline,
  ExclamationTriangle: uniExclamationTriangle,
  Export: uniExport,
  Eye: uniEye,
  EyeSlash: uniEyeSlash,
  FileAlt: uniFileAlt,
  FileExport: uniFileExport,
  FileInfoAlt: uniFileInfoAlt,
  Filter: uniFilter,
  Focus: uniFocus,
  FocusTarget: uniFocusTarget,
  Folder: uniFolder,
  Font: uniFont,
  Globe: uniGlobe,
  Hdd: uniHdd,
  History: uniHistory,
  Home: uniHome,
  Image: uniImage,
  ImageCheck: uniImageCheck,
  ImagePlus: uniImagePlus,
  ImageResizeLandscape: uniImageResizeLandscape,
  InfoCircle: uniInfoCircle,
  KeyholeSquare: uniKeyholeSquareFull,
  Link: uniLink,
  ListOl: uniListOl,
  ListUl: uniListUl,
  LocationArrowAlt: uniLocationArrowAlt,
  LocationPoint: uniLocationPoint,
  Map: uniMap,
  MapMarker: uniMapMarker,
  MapMarkerInfo: uniMapMarkerInfo,
  MapPin: uniMapPin,
  Minus: uniMinus,
  Music: uniMusic,
  NoImage: uniImageSlash,
  Pause: uniPause,
  Play: uniPlay,
  Plus: uniPlus,
  PlusCircle: uniPlusCircle,
  Process: uniProcess,
  Processor: uniProcessor,
  QuestionCircle: uniQuestionCircle,
  Redo: uniRedo,
  Save: uniSave,
  SearchGlass: uniSearch,
  SearchMinus: uniSearchMinus,
  SearchPlus: uniSearchPlus,
  Settings: uniSetting,
  SignOut: uniSignout,
  Sort: uniSort,
  SortDown: uniSortAmountDown,
  SortUp: uniSortAmountUp,
  SquareFull: uniSquareFull,
  Swatchbook: uniSwatchbook,
  Tag: uniTag,
  Text: uniText,
  Trash: uniTrashAlt,
  Update: uniFileEditAlt,
  Upload: uniCloudUpload,
  User: uniUser,
  UserCircle: uniUserCircle,
  UserSquare: uniUserSquare,
  VideoSlash: uniVideoSlash,
  WindowGrid: uniWindowGrid,
  WindowMaximize: uniWindowMaximize,
  Copy: uniCopy,
  Keyboard: uniKeyboard,
};
