<template>
  <RepetitiveFlow
    :open="isOpen"
    :config="config"
    @close="closeModal(TypeModals.GuidedFlow)"
    @finished="onFinished"
  />
</template>

<script setup lang="ts">
// NOTE: `TypeModals.GuidedFlow` and `GetRepetitiveFormDocument` are referenced
// here but do NOT exist yet — they will be generated by `task generate` once
// the corresponding GraphQL schema additions land.  This file will not
// typecheck or build until that step is completed.

import { computed } from "vue";
import { useRouter } from "vue-router";
import { useQuery } from "@vue/apollo-composable";
import { TypeModals } from "@/generated-types/queries";
import { GetRepetitiveFormDocument } from "@/generated-types/queries";
import { useBaseModal } from "@/composables/useBaseModal";
import { toRepetitiveFormConfig } from "@/composables/useRepetitiveFlowConfig";
import RepetitiveFlow from "@/components/repetitiveForm/RepetitiveFlow.vue";
import type { RepetitiveFormConfig } from "@/composables/useRepetitiveForm";

const { getModalInfo, closeModal } = useBaseModal();
const router = useRouter();

const isOpen = computed(() => getModalInfo(TypeModals.GuidedFlow).open);

// Run the GetRepetitiveForm query with the fixed name "omnibus".
// The query result shape must match RepetitiveFormConfig (plus __typename fields).
const { result } = useQuery(GetRepetitiveFormDocument, { name: "omnibus" });

const config = computed<RepetitiveFormConfig>(() => {
  const raw = result.value?.GetRepetitiveForm;
  if (!raw) {
    // Return a safe empty config while the query is loading.
    return { repeatable: false, steps: [] };
  }
  return toRepetitiveFormConfig(raw);
});

const onFinished = (entity: { id?: string; uuid?: string }) => {
  closeModal(TypeModals.GuidedFlow);

  const entityId = entity.id ?? entity.uuid;
  if (entityId) {
    // TODO: replace "SingleEntity" with the correct named route if it differs,
    // and supply the entity `type` param once it is available from the query result.
    router.push({ name: "SingleEntity", params: { id: entityId } });
  }
};
</script>
